name: catalyst_center_app
description: "A brief description of the Catalyst Center App."
publish_to: 'none'

version: 1.0.0

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.16.0

flutter:
  uses-material-design: true